## APT Install packages
- name: Installing a list of packages for Precise or older
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - "linux-image-extra-{{ lookup('pipe', 'uname -r') }}"
      - linux-image-extra-virtual