## APT Install packages
- name: Installing a list of packages for Jessie or newer
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - gnupg2
      - software-properties-common