---
# tasks file for repository
## APT Update packages
- name: Upadting packages if needed
  apt:
    cache_valid_time: 3600

## APT Key
- name: Adding Dotdeb APT Key
  apt_key:
    url: https://www.dotdeb.org/dotdeb.gpg

## APT Repository
### Debian Repository
- name: Debian repository
  include_tasks: debian/main.yml
  when: ansible_distribution == 'Debian'

### Ubuntu Repository
- name: Ubuntu repository
  include_tasks: ubuntu/main.yml
  when: ansible_distribution == 'Ubuntu'

## APT Install Aptitude
- name: Installing Aptitude
  apt:
    name: aptitude
    state: latest


## APT Upgrade
- name: Upgrading packages
  apt:
    upgrade: yes