---
# tasks file for repository

## APT Key
- name: Adding Dotdeb APT Key
  apt_key:
    url: https://www.dotdeb.org/dotdeb.gpg

## APT Repository
### Debian Repository
- name: Debian repository
  include_tasks: debian/main.yml
  when: ansible_distribution == 'Debian'

### Ubuntu Repository
- name: Ubuntu repository
  include_tasks: ubuntu/main.yml
  when: ansible_distribution == 'Ubuntu'

## APT Update
- name: Updating packages
  apt:
    update_cache: yes

## APT Install Aptitude
- name: Installing Aptitude
  apt:
    name: aptitude
    state: latest


## APT Upgrade
- name: Upgrading packages
  apt:
    upgrade: yes