---
# Backports repository
- name : Backports repository
  apt_repository:
    repo: "{{ item }} http://ports.ubuntu.com/ubuntu-ports {{ ansible_distribution_release }}-backports main restricted universe multiverse"
    filename: backports
    update_cache: no
  with_items:
    - deb
    - deb-src
