---
# Dotdeb repository
- name : Dotdeb repository
  apt_repository:
    repo: "{{ item }} http://packages.dotdeb.org stable all"
    filename: dotdeb
    update_cache: no
  with_items:
    - deb
    - deb-src

## ARM Architecture
- name: ARM Architecture
  include_tasks: arm.yml
  when: dpkg_architecture in ['armhf', 'arm64']

## Other Architecture
- name: Other Architecture
  include_tasks: other.yml
  when: dpkg_architecture not in ['armhf', 'arm64']

