---
# Dotdeb repository
- name : Dotdeb repository
  apt_repository:
    repo: "{{ item }} http://packages.dotdeb.org stable all"
    filename: dotdeb
    update_cache: no
  with_items:
    - deb
    - deb-src

## ARM CPU
- name: ARM CPU
  include_tasks: arm.yml
  when: dpkg_architecture in ['armhf', 'arm64']

## Other CPU
- name: Other CPU
  include_tasks: others.yml
  when: dpkg_architecture not in ['armhf', 'arm64']

