---
# Dotdeb repository
- name : Adding Dotdeb repository
  apt_repository:
    repo: "{{ item }} http://packages.dotdeb.org {{ ansible_distribution_release }} all"
    filename: dotdeb
  with_items:
    - deb
    - deb-src

# Backports repository
- name : Adding Backports repository
  apt_repository:
    repo: "{{ item }} http://deb.debian.org/debian {{ ansible_distribution_release }}-backports main contrib non-free"
    filename: backports
  with_items:
    - deb
    - deb-src

