---
# tasks file for docker
## APT Update packages
- name: Upadte packages if needed
  apt:
    cache_valid_time: 3600

# tasks file for docker
## APT Remove packages
- name: Remove a list of packages
  apt:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
      - docker
      - docker-engine
      - docker.io

## APT Install packages
### Debian Packages
- name: Debian packages
  include_tasks: debian/main.yml
  when: ansible_distribution == 'Debian'

### Ubuntu Packages
- name: Ubuntu packages
  include_tasks: ubuntu/main.yml
  when: ansible_distribution == 'Ubuntu'

## APT Key
- name: Docker APT Key
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution|lower }}/gpg"

## Adding Docker Repository
- name: Docker Repository
  apt_repository:
    repo: "deb [arch={{ dpkg_architecture }}] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
  when: dpkg_architecture in ['amd64', 'armhf'] or
        ansible_distribution == 'Ubuntu' and ansible_lsb['major_release']|int >= 16 and dpkg_architecture in ['ppc64el', 's390x']



## APT Update and Install Docker
- name: Install Docker
  apt:
    name: docker-ce
    update_cache: yes